name: Code Quality Checks

on:
  push

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install 3rd party dependencies
        run: sudo apt-get update && sudo apt-get install -y direnv graphviz libgraphviz-dev pkg-config

      - name: Install Python
        run: sudo apt-get install -y python3 python3-pip

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment with uv
        run: uv venv .venv

      - name: Install Python dependencies with uv
        run: uv pip install ruff

      - name: Run quality checks
        shell: bash
        run: |
          cp .env.example .env
          direnv allow
          uv run ruff check src ./appendix/tests notebooks
